title: thororen
description: About Me
author: Shangzhi Huang
avatar: /logo.png
email: ngzhio@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

twitter:
  username: thororen
  card: summary
logo: logo.png
social:
  name: thororen
  links:
    - https://twitter.com/thororen
    - https://github.com/thororen1234
lang: en

